/usr/local/fsl/bin/run_first -i pass9_13_t1 -t pass9_13_t1_to_std_sub.mat -n 50 -o test-L_Accu_first -m /usr/local/fsl/data/first/models_336_bin/L_Accu_bin.bmv; /usr/local/fsl/bin/first_boundary_corr -s test-L_Accu_first -o test-L_Accu_corr -i pass9_13_t1 -b fast
/usr/local/fsl/bin/run_first -i pass9_13_t1 -t pass9_13_t1_to_std_sub.mat -n 50 -o test-L_Amyg_first -m /usr/local/fsl/data/first/models_336_bin/intref_thal/L_Amyg.bmv -intref /usr/local/fsl/data/first/models_336_bin/05mm/L_Thal_05mm.bmv; /usr/local/fsl/bin/first_boundary_corr -s test-L_Amyg_first -o test-L_Amyg_corr -i pass9_13_t1 -b fast
/usr/local/fsl/bin/run_first -i pass9_13_t1 -t pass9_13_t1_to_std_sub.mat -n 30 -o test-L_Hipp_first -m /usr/local/fsl/data/first/models_336_bin/intref_thal/L_Hipp.bmv -intref /usr/local/fsl/data/first/models_336_bin/05mm/L_Thal_05mm.bmv; /usr/local/fsl/bin/first_boundary_corr -s test-L_Hipp_first -o test-L_Hipp_corr -i pass9_13_t1 -b fast
/usr/local/fsl/bin/run_first -i pass9_13_t1 -t pass9_13_t1_to_std_sub.mat -n 40 -o test-L_Pall_first -m /usr/local/fsl/data/first/models_336_bin/05mm/L_Pall_05mm.bmv; /usr/local/fsl/bin/first_boundary_corr -s test-L_Pall_first -o test-L_Pall_corr -i pass9_13_t1 -b none
/usr/local/fsl/bin/run_first -i pass9_13_t1 -t pass9_13_t1_to_std_sub.mat -n 40 -o test-L_Puta_first -m /usr/local/fsl/data/first/models_336_bin/05mm/L_Puta_05mm.bmv; /usr/local/fsl/bin/first_boundary_corr -s test-L_Puta_first -o test-L_Puta_corr -i pass9_13_t1 -b none
/usr/local/fsl/bin/run_first -i pass9_13_t1 -t pass9_13_t1_to_std_sub.mat -n 40 -o test-L_Thal_first -m /usr/local/fsl/data/first/models_336_bin/05mm/L_Thal_05mm.bmv; /usr/local/fsl/bin/first_boundary_corr -s test-L_Thal_first -o test-L_Thal_corr -i pass9_13_t1 -b none
/usr/local/fsl/bin/run_first -i pass9_13_t1 -t pass9_13_t1_to_std_sub.mat -n 50 -o test-R_Accu_first -m /usr/local/fsl/data/first/models_336_bin/R_Accu_bin.bmv; /usr/local/fsl/bin/first_boundary_corr -s test-R_Accu_first -o test-R_Accu_corr -i pass9_13_t1 -b fast
/usr/local/fsl/bin/run_first -i pass9_13_t1 -t pass9_13_t1_to_std_sub.mat -n 50 -o test-R_Amyg_first -m /usr/local/fsl/data/first/models_336_bin/intref_thal/R_Amyg.bmv -intref /usr/local/fsl/data/first/models_336_bin/05mm/R_Thal_05mm.bmv; /usr/local/fsl/bin/first_boundary_corr -s test-R_Amyg_first -o test-R_Amyg_corr -i pass9_13_t1 -b fast
/usr/local/fsl/bin/run_first -i pass9_13_t1 -t pass9_13_t1_to_std_sub.mat -n 30 -o test-R_Caud_first -m /usr/local/fsl/data/first/models_336_bin/intref_thal/R_Caud.bmv -intref /usr/local/fsl/data/first/models_336_bin/05mm/R_Thal_05mm.bmv; /usr/local/fsl/bin/first_boundary_corr -s test-R_Caud_first -o test-R_Caud_corr -i pass9_13_t1 -b fast
/usr/local/fsl/bin/run_first -i pass9_13_t1 -t pass9_13_t1_to_std_sub.mat -n 30 -o test-R_Hipp_first -m /usr/local/fsl/data/first/models_336_bin/intref_thal/R_Hipp.bmv -intref /usr/local/fsl/data/first/models_336_bin/05mm/R_Thal_05mm.bmv; /usr/local/fsl/bin/first_boundary_corr -s test-R_Hipp_first -o test-R_Hipp_corr -i pass9_13_t1 -b fast
/usr/local/fsl/bin/run_first -i pass9_13_t1 -t pass9_13_t1_to_std_sub.mat -n 40 -o test-R_Pall_first -m /usr/local/fsl/data/first/models_336_bin/05mm/R_Pall_05mm.bmv; /usr/local/fsl/bin/first_boundary_corr -s test-R_Pall_first -o test-R_Pall_corr -i pass9_13_t1 -b none
/usr/local/fsl/bin/run_first -i pass9_13_t1 -t pass9_13_t1_to_std_sub.mat -n 40 -o test-R_Puta_first -m /usr/local/fsl/data/first/models_336_bin/05mm/R_Puta_05mm.bmv; /usr/local/fsl/bin/first_boundary_corr -s test-R_Puta_first -o test-R_Puta_corr -i pass9_13_t1 -b none
/usr/local/fsl/bin/run_first -i pass9_13_t1 -t pass9_13_t1_to_std_sub.mat -n 40 -o test-R_Thal_first -m /usr/local/fsl/data/first/models_336_bin/05mm/R_Thal_05mm.bmv; /usr/local/fsl/bin/first_boundary_corr -s test-R_Thal_first -o test-R_Thal_corr -i pass9_13_t1 -b none
